name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build all build type and flavor permutations
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload to mobile.dev
        uses: mobile-dev-inc/action-upload@v2.1.0
        with:
          api-key: ${{ secrets.MOBILE_DEV_API_KEY }}
          app-file: app/build/outputs/apk/demo/debug/app-demo-debug.apk
